codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "65...90"

  status:
    project:
      default:
        target: 70%
        threshold: 2
        base: auto
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default

ignore: 
  - "src/constant" 
  - "src/index.ts"
  - "src/setupTests.ts"

codecov:
  token: 2ffe860b-be0c-4795-a348-ec5945a42864
