defaults: &defaults
  docker:
    - image: circleci/node:8.16
  working_directory: ~/repo
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}-
            - source-

      - checkout

      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/repo"

  install_dependencies:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          keys:
            - depens-{{ checksum "package.json" }}
            - depens-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: depens-{{ checksum "package.json" }}
  lint:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: depens-{{ checksum "package.json" }}
      - run: yarn lint
  test:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: depens-{{ checksum "package.json" }}
      - run: yarn test:unit

  build:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: depens-{{ checksum "package.json" }}

      - run: yarn build

      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - package.json

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Semantic Release
          command: yarn release

      - run:
          name: Aunthenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Publish package
          command: npm publish

  codecov:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: depens-{{ checksum "package.json" }}
      - run: yarn test:unit -- --coverage
      - codecov/upload:
          file: coverage/*.json
          flags: frontend
          token: 60776250-c459-4e1c-9a9a-8717fe1bc5e7

workflows:
  version: 2
  lint_and_build:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - build:
          requires:
            - lint

  test_and_coverage:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - install_dependencies
      - codecov:
          requires:
            - test

  build_and_release:
    jobs:
      - checkout_code:
          filters:
            branches:
              only:
                - master
                - develop
      - install_dependencies:
          requires:
            - checkout_code
      - test:
          requires:
            - install_dependencies
      - build:
          requires:
            - install_dependencies
      - release:
          type: approval
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
